[package]
name = "harbinger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "=0.5.0-rc.3"
har = "0.8.0"
clap = { version = "4.2.7", features = ["derive"] }
anyhow = "1.0"
dprint-plugin-typescript = "0.84.4"
deno_ast = "0.26.0"
thiserror = "1.0.40"
